import HeaderClient from '@/components/HeaderClient'
import SocialMediaLinks from '@/components/SocialMediaLinks'
import Spotlight from '@/components/Spotlight'
import ThemeProvider from '@/context/ThemeProvider'
import { getAllPages } from '@/data/getAllPages'
import { Analytics } from '@vercel/analytics/react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pages = await getAllPages()

  return (
    <html lang="en">
      <head>
        <title>IGOR N FAUSTINO</title>
      </head>
      <body
        className={`${inter.className} bg-slate-300 text-base text-theme-grey accent-theme-primary dark:bg-theme-grey dark:text-slate-100`}
      >
        <ThemeProvider>
          <Spotlight>
            <div
              className={`${inter.className} flex min-h-screen flex-col items-center justify-between`}
            >
              <HeaderClient pages={pages} />
              <div className="container max-w-2xl pb-16 pt-16">{children}</div>
              <SocialMediaLinks />
            </div>
          </Spotlight>
        </ThemeProvider>
        <Analytics />
      </body>
    </html>
  )
}
